### ISSUE TITLE
여기다 올리면 되나요?ㅎㅎ

### ISSUE THREAD

**Issue by sunmin0305** [tokyo-creator-club/designers#2]
![2song_tokyocg](https://cloud.githubusercontent.com/assets/9493355/14170646/cca4d0a2-f769-11e5-833a-d1a9974b2686.jpg)

작업해야지 작업해야지 하다가 오늘 30분이 남아서 작업했어요 ㅎㅎㅎ
중간에 갑자기 수정들어와서 과연 완성할 수 있을까 긴장...했지만 다행이네요 ㅎㅎ
일하다가 다운받은것들로 슥슥슥:9
다음번에는 성의껏 만들어볼게요..ㅎㅎ
활발히 활동을 안해서 제가 스타트 끊어도 될지 모르겠지만.. 잘부탁 드립니당..ㅎㅎㅎ

**Comment by sunmin0305** [comment]
아........ 이거 잘못올렸네요;;; 퇴근하고 집에서 지울게요;;;;

**Comment by img75** [comment]
@sunmin0305  오잉~ 이거 아니에용? ㅎㅎ

**Comment by img75** [comment]
@sunmin0305 다시 갱신해주시면 그걸로 적용할게요~ 감사합니다!

**Comment by sunmin0305** [comment]
파일은 그거 맞아요!! 근데 제가 새로글을 써야하는지 댓글에 달아야 하는지 몰라서ㅎㅎㅎ;; 일단 두곳에다가 다 올리고
퇴근했는데...ㅎㅎㅎ

2016年3月31日木曜日、Jeong Jinho<notifications@github.com>さんは書きました:

> @sunmin0305 <https://github.com/sunmin0305> 다시 갱신해주시면 그걸로 적용할게요~ 감사합니다!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tokyo-creator-club/designers/issues/2#issuecomment-203847792>
>


-- 
李宣ミン（イ ソンミン）
武蔵野美術大学
デザイン情報学科
s.min305@gmail.com
090-8808-4306

**Comment by img75** [comment]
@sunmin0305 반영했습니다. 이렇게 올리시는게 맞아요~ ^^
(반영 완료했기 때문에 본 이슈는 클로즈 합니다~) ^__^//
https://www.facebook.com/groups/tokyodesign/

**Comment by img75** [comment]
수정예정중이신거 같아서 다시 오픈하겠습니다 :)

**Comment by flyin98** [comment]
@sunmin0305 
오 좋은데요 봄기운이 느껴지는... 이걸보니 올해는 여친이 생길것 같은데요 ㅎㅎ
근데  구락부가...클럽아닌가요? 그룹이 아니구? ㅎㅎ

**Comment by sunmin0305** [comment]
![2song_tokyocg](https://cloud.githubusercontent.com/assets/9493355/14194833/7c82994a-f7ed-11e5-87f2-e05ca9374a1e.jpg)
오하요고자이마스!
수정본입니다 ㅎㅎ
포토샵 파일에 스마트폰용으로 제작할 수 있게 가이드라인 그려놨는데 
공유하는게 다른분들도 작업하기 편할까요?_?ㅎㅎ

**Comment by sunmin0305** [comment]
![2song_tokyocg-2](https://cloud.githubusercontent.com/assets/9493355/14194894/2181215a-f7ee-11e5-929c-3ad0b75fbfb1.jpg)
올리고보니 살짝 마음에 안들어서 수정했습니다;; ;;;;

**Comment by flyin98** [comment]
@sunmin0305 
오  좋은데요 트윙클~ 트윙클 ~ 한것이
요즘 눈이 침침 해서 그런지 서브메세지가 아저씨들한태는 잘 안보일수도 있겠는데요 ㅎㅎㅎ

**Comment by img75** [comment]
@sunmin0305 수고하셨습니다~!!! +_+ 그룹에 업로드 완료했기 때문에 이슈는 닫겠습니다.
